---
kind: Service
apiVersion: v1
metadata:
  namespace: csop-dev
  name: service-rocketmq-namesrv
  labels:
    app: service-rocketmq-namesrv
spec:
  ports:
  - protocol: TCP
    port: 9876
    targetPort: 9876
  selector:
    app: pod-rocketmq-namesrv
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  namespace: csop-dev
  name: rocketmq-namesrv
  labels:
    app: rocketmq-namesrv
spec:
  replicas: 2
  serviceName: service-rocketmq-namesrv
  selector:
    matchLabels:
      app: pod-rocketmq-namesrv
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-rocketmq-namesrv
    spec:
      nodeSelector:
        node-role.kubernetes.io/rocketmq: "true"
      hostNetwork: true
      imagePullSecrets:
      - name: harbor
      containers:
      - image: 112.124.238.67/library/rocketmq-namesrv:4.5.1
        securityContext:
          privileged: true
        imagePullPolicy: Always
        name: container-rocketmq-namesrv
        ports:
        - protocol: TCP
          containerPort: 9876

        resources:
          requests:
            cpu: 0.5
            memory: 1740Mi
          limits:
            cpu: 0.5
            memory: 2048Mi

        readinessProbe:
          tcpSocket:
            port: 9876
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          tcpSocket:
            port: 9876
          initialDelaySeconds: 120
          periodSeconds: 10

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pod-rocketmq-namesrv
              topologyKey: kubernetes.io/hostname

      dnsPolicy: ClusterFirst
      restartPolicy: Always