---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: csop-dev
  name: configmap-rocketmq-broker-slave
data:
  NAMESRV_ADDR: "rocketmq-namesrv-0.service-rocketmq-namesrv.csop-dev:9876;rocketmq-namesrv-1.service-rocketmq-namesrv.csop-dev:9876"
  BROKER_ID: "1"
  BROKER_ROLE: "SLAVE"
  STATEFULSET_NAME: "rocketmq-broker-slave"
  SEND_MESSAGE_THREAD_POOL_NUMS: "128"
---
kind: Service
apiVersion: v1
metadata:
  namespace: csop-dev
  name: service-rocketmq-broker-slave
  labels:
    app: service-rocketmq-broker-slave
spec:
  ports:
  - name: rocketmq-port-10909
    protocol: TCP
    port: 10909
    targetPort: 10909
  - name: rocketmq-port-10911
    protocol: TCP
    port: 10911
    targetPort: 10911
  selector:
    app: pod-rocketmq-broker-slave
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  namespace: csop-dev
  name: rocketmq-broker-slave
  labels:
    app: rocketmq-broker-slave
spec:
  replicas: 1
  serviceName: service-rocketmq-broker-slave
  selector:
    matchLabels:
      app: pod-rocketmq-broker-slave
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-rocketmq-broker-slave
    spec:
      nodeSelector:
        node-role.kubernetes.io/rocketmq: "true"
      imagePullSecrets:
      - name: harbor
      containers:
      - image: 112.124.238.67/library/rocketmq-broker:4.5.1
        securityContext:
          privileged: true
        imagePullPolicy: Always
        name: container-rocketmq-broker-slave
        ports:
        - protocol: TCP
          containerPort: 10909
        - protocol: TCP
          containerPort: 10911

        resources:
          requests:
            cpu: 0.5
            memory: 1.5Gi
          limits:
            cpu: 0.5
            memory: 1.5Gi

        envFrom:
        - configMapRef:
            name: configmap-rocketmq-broker-slave

        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: BROKER_IP1
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

        volumeMounts:
        - name: host-volume-rocketmq-broker-slave
          mountPath: /opt/rocketmq/store

        readinessProbe:
          tcpSocket:
            port: 10909
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          tcpSocket:
            port: 10909
          initialDelaySeconds: 120
          periodSeconds: 10

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pod-rocketmq-broker-slave
              topologyKey: kubernetes.io/hostname

      dnsPolicy: ClusterFirst
      restartPolicy: Always

      volumes:
      - name: host-volume-rocketmq-broker-slave
        hostPath:
          path: /mnt/data/rocketmq-slave
