---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
  namespace: rocketmq
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs-client
reclaimPolicy: Retain